# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python All OS

on:
  push:
    branches: [ "dev5" ]
  pull_request:
    branches: [ "dev5" ]

permissions:
  contents: read

jobs:
  build:

    #runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: ['windows-latest', 'ubuntu-18.04', 'macos-latest']
        os: ['windows-latest']
        #py: ['tigerbx', 'tigerhx', 'tigervdm']
        py: ['main']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install .
        pip install pyinstaller onnxruntime
    - name: Run Pyinstaller 1
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller -c -p ./tigerbx --icon=./tigerbx/exe/${{ matrix.py }}/ico.ico --add-data "./tigerbx/exe/onnxruntime_providers_shared.dll;onnxruntime/capi" -F ./tigerbx/${{ matrix.py }}.py
    - name: Run Pyinstaller  2
      if: matrix.os == 'ubuntu-18.04'
      run: |
        pyinstaller -c -p ./tigerbx --icon=./tigerbx/exe/${{ matrix.py }}/ico.ico --add-data ./tigerbx/exe/libonnxruntime_providers_shared.so:onnxruntime/capi -F ./tigerbx/${{ matrix.py }}.py
    - name: Run Pyinstaller 3
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller -c -p ./tigerbx --icon=./tigerbx/exe/${{ matrix.py }}/ico.ico --add-data ./tigerbx/exe/libonnxruntime_providers_shared.so:onnxruntime/capi -F ./tigerbx/${{ matrix.py }}.py

        
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.py }}-${{ matrix.os }}
        path: dist/*
