# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python All OS

on:
  push:
    branches: [ "compile" ]
  pull_request:
    branches: [ "compile" ]

permissions:
  contents: read

jobs:
  build:

    #runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-18.04', 'macos-latest']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        pip install .
        pip install pyinstaller
    - name: Run Pyinstaller 1
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller -c --icon=./src/exe/tigerbx/ico.ico --add-data "./src/exe/tigerbx/onnxruntime_providers_shared.dll;onnxruntime/capi" -F ./src/exe/tigerbx/tigerbx.py
    - name: Run Pyinstaller  2
      if: matrix.os == 'ubuntu-18.04'
      run: |
        pyinstaller -c --icon=./src/exe/tigerbx/ico.ico --add-data ./src/exe/tigerbx/libonnxruntime_providers_shared.so:onnxruntime/capi -F ./src/exe/tigerbx/tigerbx.py
    - name: Run Pyinstaller 3
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller -c --icon=./src/exe/tigerbx/ico.ico --add-data ./src/exe/tigerbx/libonnxruntime_providers_shared.so:onnxruntime/capi -F ./src/exe/tigerbx/tigerbx.py
        
    - uses: actions/upload-artifact@v3
      with:
        name: tigerbx-${{ matrix.os }}
        path: dist/*
